"""create parcel tables

Revision ID: e155ba88af1e
Revises:
Create Date: 2026-09-18 22:20:21.817521

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e155ba88af1e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parcel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("content_cost_cents", sa.Integer(), nullable=False),
        sa.Column("delivery_cost_rub", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELED", "IN_DELIVERY", name="parcelstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["parcel_type.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parcel_user_id"), "parcel", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcel_user_id"), table_name="parcel")
    op.drop_table("parcel")
    op.drop_table("parcel_type")
    # ### end Alembic commands ###
